# Site settings
name: Ayesha Shaheen
title: Ayesha Shaheen| Software Engineer
description: Software engineer experienced in creating real-world applications and delivering seamless user experiences through thoughtful design and efficient code.
url: "https://ayeshashaheen.vercel.app"
baseurl: ""
email: ayeshashaheen542@gmail.com
cover: /img/og.jpg
logo: /img/logo-black.png
resume: /resume1.pdf
social:
  - title: email
    url: mailto:ayeshashaheen542@gmail.com
  - title: instagram
    url: https://instagram.com/sooyaaa744
  - title: github
    url: https://github.com/AyeshaShaheen03
  - title: linkedin
    url: https://www.linkedin.com/in/ayesha-shaheen1/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
